<a href="https://colab.research.google.com/github/erkamalkumar/Kamal/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Title Here

An short introduction about PyTorch and about the chosen functions. 

- function 1: is_tensor
- function 2: is_storage
- function 3: is_complex
- function 4: conj
- function 5: is_floating_point

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cpu (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, 1.11.0+cu113, 1.11.0+cu115, 1.11.0+rocm4.3.1, 1.11.0+rocm4.5.2, 1.12.0, 1.12.0+cpu, 1.12.0+cu102, 1.12.0+cu113, 1.12.0+cu116, 1.12.0+rocm5.0, 1.12.0+rocm5.1.1, 1.12.1, 1.12.1+cpu, 1.12.1+cu102, 1.12.1+cu113, 1.12.1+cu116, 1.12.1+rocm5.0, 1.12.1+rocm5.1.1, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.0+rocm5.1.1, 1.13.0+rocm5.2, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 1.13.1+cu117.with.pypi.cudnn, 1.13.1+rocm5.1.1, 1.13.1+rocm5.2, 2.0.0, 2.0.0+cpu, 2.0.0+cpu.cxx11.abi, 2.0.0+cu117, 2.0.0+cu117.with.pypi.cudnn, 2.0.0+cu118, 2.0.0+rocm5.3, 2.0.0+rocm5.4.2)
ERROR: No matching distribution found for torch==1.7.0+cpu


In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.is_tensor()

```
torch.is_tensor() is a function in the PyTorch library 
that can be used to check whether a given variable is a PyTorch tensor or not.
```

In [3]:
# Example 1 - working (change this)
x1 = torch.is_tensor(torch.tensor([[1, 2], [3, 4.]]))
x1

True

Explanation about example:

```
In the above example we have taken a tensor inside the torch.is_tensor(),
and we are getting result as True.


In [4]:
# Example 2 - working
x = [[1, 2], [3, 4.]]
x2 = torch.is_tensor(x)
x2

False

Explanation about example:
```
In the above example we have considered a list inside the torch.is_tensor(),
and getting output as False because x is not a tensor.
 

In [5]:
# Example 3 - breaking (to illustrate when it breaks)
x3 = torch.is_tensor(torch.tensor([[1, 2], [3, 4, 5]]))
x3

ValueError: ignored

Explanation about example:
```
In above example we have not define tensor properly inside the torch.is_tensor()
that's why we are getting value error.


Closing comments about when to use this function:
```
torch.is_tensor() function that takes an input object and returns a boolean value
indicating whether the object is a PyTorch tensor or not. If the input is a
PyTorch tensor, the function will return True, otherwise it will return False.


Let's save our work using Jovian before continuing.

In [6]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [7]:
import jovian

In [8]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - torch.is_storage()
```
torch.is_storage() is a function in PyTorch that checks whether an object is a
PyTorch storage object or not. Because a storage object in PyTorch is a
contiguous chunk of memory used to store tensor elements.


In [9]:
# Example 1 - working

# A constant tensor of size n
a = torch.FloatStorage(6)
print(a)  

# Applying the is_storage function and 
x1 = torch.is_storage(a)
print(x1)

 -7.55476626589991e-18
 4.5693540324703635e-41
 5.877692159302217e-34
 0.0
 0.0
 0.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
True


<ipython-input-9-fbd975598bfe>:4: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a = torch.FloatStorage(6)
<ipython-input-9-fbd975598bfe>:5: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(a)
/usr/local/lib/python3.10/dist-packages/torch/storage.py:636: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() inst

Explanation about example:
```
In the above example we have created variable a with floatstorage.
then we have checked using torch.is_storage(), and got output as Ture.


In [10]:
# Example 2 - working

a = torch.randn(4, 6)
print(a)
  
# Applying the is_storage function and 
x2 = torch.is_storage(a)
print(x2)



tensor([[ 1.3227e+00,  6.9113e-01, -4.4679e-01,  6.5395e-01, -7.5634e-01,
          1.4147e+00],
        [-1.4116e+00,  3.2557e-01, -1.6259e+00,  8.8110e-04, -1.2268e+00,
         -1.7513e+00],
        [ 1.0023e+00, -1.8031e-01,  1.3427e+00,  5.1949e-01,  1.4331e+00,
         -6.2914e-01],
        [ 1.0424e+00,  2.1939e+00, -1.0019e+00,  4.5391e-01, -1.5870e+00,
         -4.2063e-01]])
False


Explanation about example:

```
In the above example torch.randn() function generates a tensor
with random values, and is not a storage object. 
The torch.is_storage() function checks whether an object is a 
PyTorch storage object, not a tensor so it's gives output as False.


In [11]:
# Example 3 - breaking (to illustrate when it breaks)

x3 = 5
torch.is_storage(x3)

False

Explanation about example:
```
In the above example we have taken non tensor value and then checking using torch.is_storage()


Closing comments about when to use this function:

```
In general, torch.is_storage() will not raise any errors on its own, 
but you should ensure that the input argument is a 
PyTorch storage object before using it in storage-related operations.


In [12]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 3 - torch.is_complex()

```
torch.is_complex() is a function in PyTorch that checks whether a given tensor
or element-wise scalar input is complex or not. 
It returns a Boolean tensor of the same shape as the input tensor, 
where each element is True if the corresponding element in the 
input tensor is a complex number, and False otherwise.


In [13]:
# Example 1 - working

# creating a tensor x with complex values
x = torch.tensor([2+3j, 4-2j, 1+0j])

# check if the tensor contains complex values
x1 = torch.is_complex(x)

print(x)
print(x1)

tensor([2.+3.j, 4.-2.j, 1.+0.j])
True


Explanation about example:
```
As we can see that we have taken complex values in tensor x,
and then we have checked using torch.is_complex() function.


In [14]:
# Example 2 - working

# creating a tensor with both real and complex values
x = torch.tensor([2, 3.5, 1+0j, 4-3j])

# check if the tensor contains complex values
x2 = torch.is_complex(x)

print(x)
print(x2)

tensor([2.0000+0.j, 3.5000+0.j, 1.0000+0.j, 4.0000-3.j])
True


Explanation about example:
```
Even though the first two elements of x are real numbers, 
they are automatically promoted to a complex type (specifically, 
torch.complex128) by PyTorch when combined with the complex elements in x.


In [15]:
# Example 3 - breaking (to illustrate when it breaks)

x = 3 + 2j

# try to check if the scalar is complex
is_complex = torch.is_complex(x)

TypeError: ignored

Explanation about example:

```
In the above example we can see that, the error message states that 
torch.is_complex() expected a Tensor input but received a complex object instead. 
Therefore, we should always make sure that the input to torch.is_complex() is a valid PyTorch tensor.


Closing comments about when to use this function:
```
torch.is_complex() will not break or raise an error if the input tensor is a valid PyTorch tensor. 
However, if the input tensor is not a valid tensor, then torch.is_complex() will raise a 
TypeError with an appropriate error message.


In [16]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - torch.conj()
```
The torch.conj(), function returns the complex conjugate of a tensor. 
This function applies the complex conjugate operation element-wise to a tensor,
effectively flipping the sign of the imaginary part of each complex element. 


In [17]:
# Example 1 - working

# creating a tensor with both real and complex values
x = torch.tensor([2, 3.5, 1+2j, 4-3j])

# compute the complex conjugate of x
x1 = torch.conj(x)

print(x)
print(x1)

tensor([2.0000+0.j, 3.5000+0.j, 1.0000+2.j, 4.0000-3.j])
tensor([2.0000-0.j, 3.5000-0.j, 1.0000-2.j, 4.0000+3.j])


Explanation about example:
```
In this example, we created a tensor x that has both real and complex values. 
We then used torch.conj() to compute the complex conjugate of x, 
which is a new tensor that has the same shape as x but with the 
signs of the imaginary parts of the complex elements flipped. 


In [18]:
# Example 2 - working

y = torch.tensor([2, 4, 1, 4-3j])

x2 = torch.conj(y)

print(y)


tensor([2.+0.j, 4.+0.j, 1.+0.j, 4.-3.j])


```
In this example, we created a tensor y that has both real and complex values.
We then used torch.conj() to compute the complex conjugate of y, which is a 
new tensor that has the same shape as y but with the signs of the imaginary 
parts of the complex elements flipped.


```



In [21]:
# Example 3 - breaking (to illustrate when it breaks)

# a tensor with only real values
x = torch.tensor([2, 3.5, 1, 4])

# try to compute the complex conjugate of x
x3 = torch.conj(x)
x3

tensor([2.0000, 3.5000, 1.0000, 4.0000])

Explanation about example

```
As we can see, that we have given a noraml tensor instead of conjugate,
then it's giving same tensor without any change.


Closing comments about when to use this function

```
torch.conj() is a PyTorch function that returns the complex conjugate of the 
input tensor. It only works with complex tensors, and will raise a 
RuntimeError if called with a non-complex tensor.



In [22]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - torch.is_floating_point()

```
torch.is_floating_point() is a built-in PyTorch function that returns 
True if the given tensor has a floating point data type, and False otherwise.


In [24]:
# Example 1 - working

y = torch.tensor([2, 3, 1])

x1 = torch.is_floating_point(y)
print(y)
x1

tensor([2, 3, 1])


False

Explanation about example:

```
In the above example we created y tensor without floating point number,
and getting output as False.


In [25]:
# Example 2 - working

y = torch.tensor([2.5, 3.6, 1.4])

x2 = torch.is_floating_point(y)
print(y)
x2

tensor([2.5000, 3.6000, 1.4000])


True

Explanation about example

```
In the above example we have created tensor y with floating point number,
and getting output as True.


In [30]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.tensor([8, 2, 4])

# try to divide x by 2.0
y = x / 2.0
x3 = torch.is_floating_point(y)
y3 = torch.is_floating_point(x)
print('Before dividing',y3)
print('After dividing',x3)


Before dividing False
After dividing True


Explanation about example:

```
In the above example we have created a tensor x and then divide by 2.0 and 
storing the result into y, and after checking the type for both before dividing
and after dividing we are getting False and True respectivaly.


Closing comments about when to use this function:
```
torch.is_floating_point() does not raise any errors on its own. 
It simply returns a boolean value indicating whether the input 
tensor has a floating point data type or not.


In [31]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion
unction 1: is_tensor
function 2: is_storage
function 3: is_complex
function 4: conj
function 5: is_floating_point

```
In this notebook we have learn about five most important tensor functions which
are torch.is_tensor(), torch.is_storage(), torch.is_complex(), torch.conj(), 
and torch.is_floating_point(). Next we will try to learn about Image processing 
using pytorch.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [32]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
